def getHeatMapData(businessType): 
    data = {
   "Health & Medical":{
      "data":[
         {
            "count":1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":7306,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":2,
            "state":"CA",
            "code":"6"
         },
         {
            "count":98,
            "state":"IL",
            "code":"17"
         },
         {
            "count":1098,
            "state":"NC",
            "code":"37"
         },
         {
            "count":3901,
            "state":"NV",
            "code":"32"
         },
         {
            "count":685,
            "state":"OH",
            "code":"39"
         },
         {
            "count":3,
            "state":"OR",
            "code":"41"
         },
         {
            "count":638,
            "state":"PA",
            "code":"42"
         },
         {
            "count":73,
            "state":"SC",
            "code":"45"
         },
         {
            "count":1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":316,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"NY",
            "code":"36"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"CO",
            "code":"8"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IN",
            "code":"18"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Bars":{
      "data":[
         {
            "count":2787,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":9,
            "state":"CO",
            "code":"8"
         },
         {
            "count":152,
            "state":"IL",
            "code":"17"
         },
         {
            "count":14,
            "state":"IN",
            "code":"18"
         },
         {
            "count":1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":1103,
            "state":"NC",
            "code":"37"
         },
         {
            "count":2319,
            "state":"NV",
            "code":"32"
         },
         {
            "count":1425,
            "state":"OH",
            "code":"39"
         },
         {
            "count":3,
            "state":"OR",
            "code":"41"
         },
         {
            "count":1071,
            "state":"PA",
            "code":"42"
         },
         {
            "count":50,
            "state":"SC",
            "code":"45"
         },
         {
            "count":505,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"NY",
            "code":"36"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"CA",
            "code":"6"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Shopping":{
      "data":[
         {
            "count":9503,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":1,
            "state":"CO",
            "code":"8"
         },
         {
            "count":1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":356,
            "state":"IL",
            "code":"17"
         },
         {
            "count":11,
            "state":"IN",
            "code":"18"
         },
         {
            "count":1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":2396,
            "state":"NC",
            "code":"37"
         },
         {
            "count":5894,
            "state":"NV",
            "code":"32"
         },
         {
            "count":2,
            "state":"NY",
            "code":"36"
         },
         {
            "count":2185,
            "state":"OH",
            "code":"39"
         },
         {
            "count":14,
            "state":"OR",
            "code":"41"
         },
         {
            "count":1755,
            "state":"PA",
            "code":"42"
         },
         {
            "count":95,
            "state":"SC",
            "code":"45"
         },
         {
            "count":958,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"CA",
            "code":"6"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Nightlife":{
      "data":[
         {
            "count":2356,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":9,
            "state":"CO",
            "code":"8"
         },
         {
            "count":132,
            "state":"IL",
            "code":"17"
         },
         {
            "count":10,
            "state":"IN",
            "code":"18"
         },
         {
            "count":1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":921,
            "state":"NC",
            "code":"37"
         },
         {
            "count":2197,
            "state":"NV",
            "code":"32"
         },
         {
            "count":1351,
            "state":"OH",
            "code":"39"
         },
         {
            "count":1,
            "state":"OR",
            "code":"41"
         },
         {
            "count":970,
            "state":"PA",
            "code":"42"
         },
         {
            "count":34,
            "state":"SC",
            "code":"45"
         },
         {
            "count":472,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"NY",
            "code":"36"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"CA",
            "code":"6"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Food":{
      "data":[
         {
            "count":11072,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":28,
            "state":"CA",
            "code":"6"
         },
         {
            "count":25,
            "state":"CO",
            "code":"8"
         },
         {
            "count":196,
            "state":"FL",
            "code":"12"
         },
         {
            "count":658,
            "state":"IL",
            "code":"17"
         },
         {
            "count":61,
            "state":"IN",
            "code":"18"
         },
         {
            "count":31,
            "state":"MO",
            "code":"29"
         },
         {
            "count":4166,
            "state":"NC",
            "code":"37"
         },
         {
            "count":7431,
            "state":"NV",
            "code":"32"
         },
         {
            "count":11,
            "state":"NY",
            "code":"36"
         },
         {
            "count":5039,
            "state":"OH",
            "code":"39"
         },
         {
            "count":29,
            "state":"OR",
            "code":"41"
         },
         {
            "count":3842,
            "state":"PA",
            "code":"42"
         },
         {
            "count":231,
            "state":"SC",
            "code":"45"
         },
         {
            "count":282,
            "state":"VA",
            "code":"51"
         },
         {
            "count":1619,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Automotive":{
      "data":[
         {
            "count":1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":5037,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":141,
            "state":"IL",
            "code":"17"
         },
         {
            "count":2,
            "state":"IN",
            "code":"18"
         },
         {
            "count":1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":1065,
            "state":"NC",
            "code":"37"
         },
         {
            "count":2849,
            "state":"NV",
            "code":"32"
         },
         {
            "count":3,
            "state":"NY",
            "code":"36"
         },
         {
            "count":1068,
            "state":"OH",
            "code":"39"
         },
         {
            "count":8,
            "state":"OR",
            "code":"41"
         },
         {
            "count":801,
            "state":"PA",
            "code":"42"
         },
         {
            "count":75,
            "state":"SC",
            "code":"45"
         },
         {
            "count":354,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"CO",
            "code":"8"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"CA",
            "code":"6"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Beauty & Spas":{
      "data":[
         {
            "count":6808,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":2,
            "state":"CA",
            "code":"6"
         },
         {
            "count":2,
            "state":"CO",
            "code":"8"
         },
         {
            "count":196,
            "state":"IL",
            "code":"17"
         },
         {
            "count":7,
            "state":"IN",
            "code":"18"
         },
         {
            "count":1726,
            "state":"NC",
            "code":"37"
         },
         {
            "count":4290,
            "state":"NV",
            "code":"32"
         },
         {
            "count":1447,
            "state":"OH",
            "code":"39"
         },
         {
            "count":5,
            "state":"OR",
            "code":"41"
         },
         {
            "count":1122,
            "state":"PA",
            "code":"42"
         },
         {
            "count":87,
            "state":"SC",
            "code":"45"
         },
         {
            "count":1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":540,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"NY",
            "code":"36"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Home Services":{
      "data":[
         {
            "count":8839,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":1,
            "state":"CA",
            "code":"6"
         },
         {
            "count":1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":211,
            "state":"IL",
            "code":"17"
         },
         {
            "count":1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":1435,
            "state":"NC",
            "code":"37"
         },
         {
            "count":4592,
            "state":"NV",
            "code":"32"
         },
         {
            "count":1,
            "state":"NY",
            "code":"36"
         },
         {
            "count":865,
            "state":"OH",
            "code":"39"
         },
         {
            "count":2,
            "state":"OR",
            "code":"41"
         },
         {
            "count":786,
            "state":"PA",
            "code":"42"
         },
         {
            "count":75,
            "state":"SC",
            "code":"45"
         },
         {
            "count":1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":471,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FL",
            "code":"12"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"VA",
            "code":"51"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"CO",
            "code":"8"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"IN",
            "code":"18"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MO",
            "code":"29"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   },
   "Restaurants":{
      "data":[
         {
            "count":11072,
            "state":"AZ",
            "code":"4"
         },
         {
            "count":118,
            "state":"CA",
            "code":"6"
         },
         {
            "count":25,
            "state":"CO",
            "code":"8"
         },
         {
            "count":67,
            "state":"FL",
            "code":"12"
         },
         {
            "count":658,
            "state":"IL",
            "code":"17"
         },
         {
            "count":61,
            "state":"IN",
            "code":"18"
         },
         {
            "count":44,
            "state":"MO",
            "code":"29"
         },
         {
            "count":4166,
            "state":"NC",
            "code":"37"
         },
         {
            "count":7431,
            "state":"NV",
            "code":"32"
         },
         {
            "count":11,
            "state":"NY",
            "code":"36"
         },
         {
            "count":5039,
            "state":"OH",
            "code":"39"
         },
         {
            "count":29,
            "state":"OR",
            "code":"41"
         },
         {
            "count":3842,
            "state":"PA",
            "code":"42"
         },
         {
            "count":231,
            "state":"SC",
            "code":"45"
         },
         {
            "count":181,
            "state":"VA",
            "code":"51"
         },
         {
            "count":1619,
            "state":"WI",
            "code":"55"
         },
         {
            "count":-1,
            "state":"code",
            "code":"id"
         },
         {
            "count":-1,
            "state":"WA",
            "code":"53"
         },
         {
            "count":-1,
            "state":"DE",
            "code":"10"
         },
         {
            "count":-1,
            "state":"DC",
            "code":"11"
         },
         {
            "count":-1,
            "state":"WV",
            "code":"54"
         },
         {
            "count":-1,
            "state":"HI",
            "code":"15"
         },
         {
            "count":-1,
            "state":"FM",
            "code":"64"
         },
         {
            "count":-1,
            "state":"WY",
            "code":"56"
         },
         {
            "count":-1,
            "state":"NH",
            "code":"33"
         },
         {
            "count":-1,
            "state":"UM",
            "code":"74"
         },
         {
            "count":-1,
            "state":"NJ",
            "code":"34"
         },
         {
            "count":-1,
            "state":"NM",
            "code":"35"
         },
         {
            "count":-1,
            "state":"TX",
            "code":"48"
         },
         {
            "count":-1,
            "state":"LA",
            "code":"22"
         },
         {
            "count":-1,
            "state":"ND",
            "code":"38"
         },
         {
            "count":-1,
            "state":"NE",
            "code":"31"
         },
         {
            "count":-1,
            "state":"TN",
            "code":"47"
         },
         {
            "count":-1,
            "state":"AK",
            "code":"2"
         },
         {
            "count":-1,
            "state":"GU",
            "code":"66"
         },
         {
            "count":-1,
            "state":"PW",
            "code":"70"
         },
         {
            "count":-1,
            "state":"VI",
            "code":"78"
         },
         {
            "count":-1,
            "state":"AL",
            "code":"1"
         },
         {
            "count":-1,
            "state":"AS",
            "code":"60"
         },
         {
            "count":-1,
            "state":"AR",
            "code":"5"
         },
         {
            "count":-1,
            "state":"VT",
            "code":"50"
         },
         {
            "count":-1,
            "state":"GA",
            "code":"13"
         },
         {
            "count":-1,
            "state":"IA",
            "code":"19"
         },
         {
            "count":-1,
            "state":"OK",
            "code":"40"
         },
         {
            "count":-1,
            "state":"ID",
            "code":"16"
         },
         {
            "count":-1,
            "state":"CT",
            "code":"9"
         },
         {
            "count":-1,
            "state":"ME",
            "code":"23"
         },
         {
            "count":-1,
            "state":"MD",
            "code":"24"
         },
         {
            "count":-1,
            "state":"MA",
            "code":"25"
         },
         {
            "count":-1,
            "state":"UT",
            "code":"49"
         },
         {
            "count":-1,
            "state":"MN",
            "code":"27"
         },
         {
            "count":-1,
            "state":"MI",
            "code":"26"
         },
         {
            "count":-1,
            "state":"MH",
            "code":"68"
         },
         {
            "count":-1,
            "state":"RI",
            "code":"44"
         },
         {
            "count":-1,
            "state":"KS",
            "code":"20"
         },
         {
            "count":-1,
            "state":"MT",
            "code":"30"
         },
         {
            "count":-1,
            "state":"MP",
            "code":"69"
         },
         {
            "count":-1,
            "state":"MS",
            "code":"28"
         },
         {
            "count":-1,
            "state":"PR",
            "code":"72"
         },
         {
            "count":-1,
            "state":"KY",
            "code":"21"
         },
         {
            "count":-1,
            "state":"SD",
            "code":"46"
         }
      ]
   }
}
    return data[businessType]
