import time

def getTrafficData(timeRange):
    data = {
        "12:00 - 13:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 13}],
        "00:00 - 01:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 1}],
        "01:00 - 02:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 2}],
        "02:00 - 03:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 3}],
        "03:00 - 04:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 4}],
        "04:00 - 05:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 5}],
        "05:00 - 06:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}]
    }
    time.sleep(3)
    return data[timeRange]
