import time

def getTrafficData(timeRange):
    data = {
        "00:00 - 01:00": 
        [{"business": "Restaurants", "value": 30},
        {"business": "Shopping", "value": 10},
        {"business": "Food", "value": 24},
        {"business": "Beauty & Spas", "value": 9},
        {"business": "Home Services", "value": 9},
        {"business": "Health & Medical", "value": 40},
        {"business": "Local Services", "value": 20},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 80},
        {"business": "Bars", "value": 75}],
        "01:00 - 02:00": 
        [{"business": "Restaurants", "value": 8},
        {"business": "Shopping", "value": 8},
        {"business": "Food", "value": 5},
        {"business": "Beauty & Spas", "value": 9},
        {"business": "Home Services", "value": 10},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 75},
        {"business": "Bars", "value": 70}],
        "02:00 - 03:00": 
        [{"business": "Restaurants", "value": 30},
        {"business": "Shopping", "value": 15},
        {"business": "Food", "value": 20},
        {"business": "Beauty & Spas", "value": 9},
        {"business": "Home Services", "value": 9},
        {"business": "Health & Medical", "value": 30},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 65},
        {"business": "Bars", "value": 50}],
        "03:00 - 04:00": 
        [{"business": "Restaurants", "value": 15},
        {"business": "Shopping", "value": 10},
        {"business": "Food", "value": 20},
        {"business": "Beauty & Spas", "value": 9},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 30},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 45},
        {"business": "Bars", "value": 30}],
        "04:00 - 05:00": 
        [{"business": "Restaurants", "value": 20},
        {"business": "Shopping", "value": 10},
        {"business": "Food", "value": 20},
        {"business": "Beauty & Spas", "value": 10},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 8},
        {"business": "Bars", "value": 8}],
        "05:00 - 06:00": 
        [{"business": "Restaurants", "value": 25},
        {"business": "Shopping", "value": 10},
        {"business": "Food", "value": 20},
        {"business": "Beauty & Spas", "value": 10},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 33},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 8},
        {"business": "Bars", "value": 8}],
        "06:00 - 07:00": 
        [{"business": "Restaurants", "value": 37},
        {"business": "Shopping", "value": 20},
        {"business": "Food", "value": 30},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 8},
        {"business": "Bars", "value": 8}],
        "07:00 - 08:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 22},
        {"business": "Health & Medical", "value": 32},
        {"business": "Local Services", "value": 29},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 8},
        {"business": "Bars", "value": 8}],
        "08:00 - 09:00": 
        [{"business": "Restaurants", "value": 40},
        {"business": "Shopping", "value": 25},
        {"business": "Food", "value": 38},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 8},
        {"business": "Bars", "value": 8}],
        "09:00 - 10:00": 
        [{"business": "Restaurants", "value": 65},
        {"business": "Shopping", "value": 54},
        {"business": "Food", "value": 57},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 37},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 5}],
        "10:00 - 11:00": 
        [{"business": "Restaurants", "value": 65},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 60},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 40},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "11:00 - 12:00": 
        [{"business": "Restaurants", "value": 63},
        {"business": "Shopping", "value": 64},
        {"business": "Food", "value": 60},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 30},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "12:00 - 13:00": 
        [{"business": "Restaurants", "value": 75},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 74},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "13:00 - 14:00": 
        [{"business": "Restaurants", "value": 95},
        {"business": "Shopping", "value": 56},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "14:00 - 15:00": 
        [{"business": "Restaurants", "value": 73},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "15:00 - 16:00": 
        [{"business": "Restaurants", "value": 64},
        {"business": "Shopping", "value": 72},
        {"business": "Food", "value": 65},
        {"business": "Beauty & Spas", "value": 65},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "16:00 - 17:00": 
        [{"business": "Restaurants", "value": 60},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 55},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 39},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "17:00 - 18:00": 
        [{"business": "Restaurants", "value": 66},
        {"business": "Shopping", "value": 80},
        {"business": "Food", "value": 56},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 30},
        {"business": "Nightlife", "value": 10},
        {"business": "Bars", "value": 30}],
        "18:00 - 19:00": 
        [{"business": "Restaurants", "value": 75},
        {"business": "Shopping", "value": 75},
        {"business": "Food", "value": 70},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 45},
        {"business": "Bars", "value": 50}],
        "19:00 - 20:00": 
        [{"business": "Restaurants", "value": 78},
        {"business": "Shopping", "value": 73},
        {"business": "Food", "value": 65},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 55},
        {"business": "Bars", "value": 56}],
        "20:00 - 21:00": 
        [{"business": "Restaurants", "value": 96},
        {"business": "Shopping", "value": 53},
        {"business": "Food", "value": 85 },
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 57},
        {"business": "Bars", "value": 66}],
        "21:00 - 22:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 43},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 67},
        {"business": "Bars", "value": 63}],
        "22:00 - 23:00": 
        [{"business": "Restaurants", "value": 84},
        {"business": "Shopping", "value": 33},
        {"business": "Food", "value": 78},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 85},
        {"business": "Bars", "value": 78}],
        "23:00 - 00:00": 
        [{"business": "Restaurants", "value": 65},
        {"business": "Shopping", "value": 20},
        {"business": "Food", "value": 50},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 88},
        {"business": "Bars", "value": 75}]
    }
    import random
    time.sleep(random.randint(1,1))
    return data[timeRange]
