import time

def getTrafficData(timeRange):
    data = {
        "00:00 - 01:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 1}],
        "01:00 - 02:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 2}],
        "02:00 - 03:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 3}],
        "03:00 - 04:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 4}],
        "04:00 - 05:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 5}],
        "05:00 - 06:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "06:00 - 07:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "07:00 - 08:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "08:00 - 09:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "09:00 - 10:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "10:00 - 11:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "11:00 - 12:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "12:00 - 13:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "13:00 - 14:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "14:00 - 15:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "15:00 - 16:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "16:00 - 17:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "17:00 - 18:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "18:00 - 19:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "19:00 - 20:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "20:00 - 21:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 6}],
        "21:00 - 22:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 13}],
        "22:00 - 23:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 13}],
        "23:00 - 00:00": 
        [{"business": "Restaurants", "value": 100},
        {"business": "Shopping", "value": 69},
        {"business": "Food", "value": 88},
        {"business": "Beauty & Spas", "value": 33},
        {"business": "Home Services", "value": 12},
        {"business": "Health & Medical", "value": 23},
        {"business": "Local Services", "value": 9},
        {"business": "Automotive", "value": 11},
        {"business": "Nightlife", "value": 7},
        {"business": "Bars", "value": 13}]
    }
    time.sleep(3)
    return data[timeRange]
